"""initial schema

Revision ID: 81a383503c7a
Revises:
Create Date: 2026-09-21 20:45:32.066448
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "81a383503c7a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("clip_count", sa.Integer(), nullable=False),
        sa.Column("total_audio_seconds", sa.Float(), nullable=False),
        sa.Column("wall_seconds", sa.Float(), nullable=False),
        sa.Column("realtime_factor", sa.Float(), nullable=False),
        sa.Column("aggregates", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_benchmark_runs_public_id"), "benchmark_runs", ["public_id"], unique=True)
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_handled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_messages_email"), "contact_messages", ["email"], unique=False)
    op.create_table(
        "corpus_clips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("selection", sa.Integer(), nullable=False),
        sa.Column("clip_name", sa.String(length=128), nullable=False),
        sa.Column("source_file", sa.String(length=255), nullable=False),
        sa.Column("noise_source", sa.String(length=64), nullable=True),
        sa.Column("raw_call_type", sa.String(length=64), nullable=False),
        sa.Column("call_type", sa.String(length=24), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("has_noise_reference", sa.Boolean(), nullable=False),
        sa.Column("has_context", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("selection", name="uq_corpus_clip_selection"),
    )
    op.create_index(op.f("ix_corpus_clips_call_type"), "corpus_clips", ["call_type"], unique=False)
    op.create_index(op.f("ix_corpus_clips_clip_name"), "corpus_clips", ["clip_name"], unique=False)
    op.create_index(op.f("ix_corpus_clips_selection"), "corpus_clips", ["selection"], unique=False)
    op.create_index(op.f("ix_corpus_clips_source_file"), "corpus_clips", ["source_file"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("artifact_key", sa.String(length=512), nullable=False),
        sa.Column("feature_count", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("positive_count", sa.Integer(), nullable=False),
        sa.Column("negative_count", sa.Integer(), nullable=False),
        sa.Column("cv_folds", sa.Integer(), nullable=False),
        sa.Column("cv_strategy", sa.String(length=120), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("f1", sa.Float(), nullable=False),
        sa.Column("roc_auc", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_versions_is_active"), "model_versions", ["is_active"], unique=False)
    op.create_index(op.f("ix_model_versions_name"), "model_versions", ["name"], unique=False)
    op.create_table(
        "recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("media_type", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_content_hash"), "recordings", ["content_hash"], unique=False)
    op.create_index("ix_recordings_origin_created", "recordings", ["origin", "created_at"], unique=False)
    op.create_index(op.f("ix_recordings_public_id"), "recordings", ["public_id"], unique=True)
    op.create_table(
        "benchmark_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("benchmark_run_id", sa.Integer(), nullable=False),
        sa.Column("clip_name", sa.String(length=128), nullable=False),
        sa.Column("call_type", sa.String(length=24), nullable=False),
        sa.Column("selected_preset", sa.String(length=48), nullable=False),
        sa.Column("candidate_score", sa.Float(), nullable=False),
        sa.Column("audio_seconds", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("used_noise_reference", sa.Boolean(), nullable=False),
        sa.Column("target_retention_pct", sa.Float(), nullable=False),
        sa.Column("machine_suppression_pct", sa.Float(), nullable=False),
        sa.Column("target_machine_gain_db", sa.Float(), nullable=False),
        sa.Column("spectral_fidelity", sa.Float(), nullable=False),
        sa.Column("core_rumble_retention_pct", sa.Float(), nullable=False),
        sa.Column("peak_in_target_band", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["benchmark_run_id"], ["benchmark_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_benchmark_results_benchmark_run_id"), "benchmark_results", ["benchmark_run_id"], unique=False
    )
    op.create_index(
        "ix_benchmark_results_run_type", "benchmark_results", ["benchmark_run_id", "call_type"], unique=False
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("requested_call_type", sa.String(length=24), nullable=False),
        sa.Column("resolved_call_type", sa.String(length=24), nullable=False),
        sa.Column("call_type_source", sa.String(length=16), nullable=False),
        sa.Column("selected_preset", sa.String(length=48), nullable=True),
        sa.Column("preset_candidates", sa.Integer(), nullable=False),
        sa.Column("candidate_score", sa.Float(), nullable=True),
        sa.Column("audio_seconds", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("realtime_factor", sa.Float(), nullable=True),
        sa.Column("cleaned_key", sa.String(length=512), nullable=True),
        sa.Column("original_spectrogram_key", sa.String(length=512), nullable=True),
        sa.Column("cleaned_spectrogram_key", sa.String(length=512), nullable=True),
        sa.Column("comparison_spectrogram_key", sa.String(length=512), nullable=True),
        sa.Column("detection_event_count", sa.Integer(), nullable=False),
        sa.Column("detection_peak_confidence", sa.Float(), nullable=True),
        sa.Column("detector_model", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_runs_public_id"), "processing_runs", ["public_id"], unique=True)
    op.create_index(
        op.f("ix_processing_runs_recording_id"), "processing_runs", ["recording_id"], unique=False
    )
    op.create_index("ix_runs_status_created", "processing_runs", ["status", "created_at"], unique=False)
    op.create_table(
        "call_detections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("peak_frequency_hz", sa.Float(), nullable=True),
        sa.Column("predicted_call_type", sa.String(length=24), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["processing_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_detections_run_id"), "call_detections", ["run_id"], unique=False)
    op.create_table(
        "run_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("target_retention_pct", sa.Float(), nullable=False),
        sa.Column("machine_suppression_pct", sa.Float(), nullable=False),
        sa.Column("target_machine_gain_db", sa.Float(), nullable=False),
        sa.Column("spectral_fidelity", sa.Float(), nullable=False),
        sa.Column("core_rumble_retention_pct", sa.Float(), nullable=False),
        sa.Column("broadband_reduction_pct", sa.Float(), nullable=False),
        sa.Column("spectral_sparsity_pct", sa.Float(), nullable=False),
        sa.Column("peak_frequency_hz", sa.Float(), nullable=False),
        sa.Column("peak_in_target_band", sa.Boolean(), nullable=False),
        sa.Column("target_band_low_hz", sa.Float(), nullable=False),
        sa.Column("target_band_high_hz", sa.Float(), nullable=False),
        sa.Column("machine_band_low_hz", sa.Float(), nullable=False),
        sa.Column("machine_band_high_hz", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["processing_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_metrics_run_id"), "run_metrics", ["run_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_metrics_run_id"), table_name="run_metrics")
    op.drop_table("run_metrics")
    op.drop_index(op.f("ix_call_detections_run_id"), table_name="call_detections")
    op.drop_table("call_detections")
    op.drop_index("ix_runs_status_created", table_name="processing_runs")
    op.drop_index(op.f("ix_processing_runs_recording_id"), table_name="processing_runs")
    op.drop_index(op.f("ix_processing_runs_public_id"), table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_index("ix_benchmark_results_run_type", table_name="benchmark_results")
    op.drop_index(op.f("ix_benchmark_results_benchmark_run_id"), table_name="benchmark_results")
    op.drop_table("benchmark_results")
    op.drop_index(op.f("ix_recordings_public_id"), table_name="recordings")
    op.drop_index("ix_recordings_origin_created", table_name="recordings")
    op.drop_index(op.f("ix_recordings_content_hash"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(op.f("ix_model_versions_name"), table_name="model_versions")
    op.drop_index(op.f("ix_model_versions_is_active"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_corpus_clips_source_file"), table_name="corpus_clips")
    op.drop_index(op.f("ix_corpus_clips_selection"), table_name="corpus_clips")
    op.drop_index(op.f("ix_corpus_clips_clip_name"), table_name="corpus_clips")
    op.drop_index(op.f("ix_corpus_clips_call_type"), table_name="corpus_clips")
    op.drop_table("corpus_clips")
    op.drop_index(op.f("ix_contact_messages_email"), table_name="contact_messages")
    op.drop_table("contact_messages")
    op.drop_index(op.f("ix_benchmark_runs_public_id"), table_name="benchmark_runs")
    op.drop_table("benchmark_runs")
    # ### end Alembic commands ###
